### ISSUE TITLE
Amazing website!

### ISSUE THREAD

**Issue by alangrainger** [handeyeco/deluge-shortcuts#5]
Thank you so much for making this. It is so clear and easy to use, especially to have on mobile as a reference next to the Deluge.

I'd like to buy you a BoD pack - how can I go about doing that - is it even possible send a private message on Github? And are the packs 2-6 still all relevant?

**Comment by handeyeco** [comment]
That's such a nice offer! Sorry I missed your message, I don't think I have GH notifications set up right.

If you or anyone else would like to buy me a BoD pack (I don't have any, so any of the six would be appreciated): I'm `@matthewcurtis` on Venmo.

Either way though, your feedback is appreciated.

**Comment by alangrainger** [comment]
Non-US person here so Venmo won't work, sorry! 😬

Paypal? Bitcoin?

**Comment by handeyeco** [comment]
Whoops, didn't realize Venmo was a US thing! Paypal: paypal.me/austincode

Again, thank you!

**Comment by alangrainger** [comment]
Sent! Thanks again :+1:
